x-airflow-common: &airflow-common
  build: .
  image: airflow_chaos:latest
  user: root
  network_mode: "host"
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@localhost:5433/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@localhost:5433/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@localhost:6380/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    KUBECONFIG: /root/.kube/config
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../src:/opt/airflow/src
    - ~/.kube/config:/root/.kube/config:ro
    - /var/run/docker.sock:/var/run/docker.sock

services:
  postgres:
    image: postgres:13
    network_mode: "host"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGPORT: 5433
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2
    network_mode: "host"
    command: redis-server --port 6380
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: >
      /bin/bash -c "
      until pg_isready -h localhost -p 5433 -U airflow; do
        echo 'Waiting for Postgres...'
        sleep 3
      done &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    depends_on:
      - postgres
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    cap_add:
    - NET_ADMIN
    command: webserver --port 8080
    depends_on:
      - airflow-init
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    depends_on:
      - airflow-init
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    depends_on:
      - airflow-init
    restart: always

volumes:
  postgres-db-volume:

networks:
  default:
    name: airflow-fresh_default