apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: social-network
    meta.helm.sh/release-namespace: social-network
  name: nginx-thrift
  namespace: social-network
  labels:
    app.kubernetes.io/managed-by: Helm
    service: nginx-thrift
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: nginx-thrift
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-thrift
        service: nginx-thrift
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape_nginxlog: "true"
        prometheus.io/port_nginxlog: "4040"
        prometheus.io/path_nginxlog: "/metrics"
    spec:
      hostname: nginx-thrift
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: nginx-thrift
        image: docker.io/yg397/openresty-thrift:xenial
        imagePullPolicy: IfNotPresent
        env:
        - name: fqdn_suffix
          value: .default.svc.cluster.local
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-thrift-config
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
        - name: nginx-thrift-config
          mountPath: /usr/local/openresty/nginx/jaeger-config.json
          subPath: jaeger-config.json
        - name: lua-scripts
          mountPath: /usr/local/openresty/nginx/lua-scripts
        - name: lua-thrift
          mountPath: /usr/local/openresty/lualib/thrift
        - name: pages
          mountPath: /usr/local/openresty/nginx/pages
        - name: gen-lua
          mountPath: /gen-lua
        - name: keys
          mountPath: /keys
        - name: nginx-logs
          mountPath: /var/log/nginx
      - name: metrics
        image: nginx/nginx-prometheus-exporter:0.11.0
        imagePullPolicy: IfNotPresent
        args:
          - -nginx.scrape-uri=http://127.0.0.1:8080/stub_status
        ports:
        - containerPort: 9113
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: nginx-log-exporter
        image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.10.0
        imagePullPolicy: IfNotPresent
        args:
          - -config-file=/etc/prometheus-nginxlog-exporter/config.yml
        ports:
        - containerPort: 4040
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
          readOnly: true
        - name: nginx-log-exporter-config
          mountPath: /etc/prometheus-nginxlog-exporter
      initContainers:
      - name: alpine-container
        image: docker.io/alpine/git:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            git clone https://github.com/dimoibiehg/DeathStarBench.git /DeathStarBench && \
            cp -r /DeathStarBench/socialNetwork/gen-lua/* /gen-lua/ && \
            cp -r /DeathStarBench/socialNetwork/docker/openresty-thrift/lua-thrift/* /lua-thrift/ && \
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/lua-scripts/* /lua-scripts/ && \
            cp -r /DeathStarBench/socialNetwork/nginx-web-server/pages/* /pages/ && \
            cp /DeathStarBench/socialNetwork/keys/* /keys/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: lua-scripts
          mountPath: /lua-scripts
        - name: lua-thrift
          mountPath: /lua-thrift
        - name: pages
          mountPath: /pages
        - name: gen-lua
          mountPath: /gen-lua
        - name: keys
          mountPath: /keys
      volumes:
      - name: nginx-thrift-config
        configMap:
          name: nginx-thrift
          defaultMode: 420
      - name: lua-scripts
        emptyDir: {}
      - name: pages
        emptyDir: {}
      - name: gen-lua
        emptyDir: {}
      - name: lua-thrift
        emptyDir: {}
      - name: keys
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: nginx-log-exporter-config
        configMap:
          name: nginx-log-exporter-config
          defaultMode: 420

