apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chaos-platform.fullname" . }}-dags
  labels:
    {{- include "chaos-platform.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/dags/*" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
